2025-06-07 16:57:29,478 - __main__ - INFO - [MainThread] - main.py:165 - Iniciando el punto de entrada de la aplicación frontend.
2025-06-07 16:57:29,507 - qdarkstyle - INFO - [MainThread] - __init__.py:270 - QSS file successfully loaded.
2025-06-07 16:57:29,533 - qdarkstyle - INFO - [MainThread] - __init__.py:173 - Found version patches to be applied.
2025-06-07 16:57:29,534 - qdarkstyle - INFO - [MainThread] - __init__.py:193 - Found application patches to be applied.
2025-06-07 16:57:29,534 - __main__ - INFO - [MainThread] - main.py:153 - Estilo oscuro aplicado.
2025-06-07 16:57:29,714 - __main__ - INFO - [Dummy-1] - main.py:70 - Worker: Obteniendo configuración de usuario...
2025-06-07 16:57:29,714 - src.ultibot_ui.services.api_client - INFO - [Dummy-1] - api_client.py:68 - Obteniendo configuración de usuario.
2025-06-07 16:57:32,045 - src.ultibot_ui.services.api_client - ERROR - [Dummy-1] - api_client.py:64 - Error de petición para GET http://localhost:8000/api/v1/config: All connection attempts failed
2025-06-07 16:57:32,045 - __main__ - ERROR - [Dummy-1] - main.py:76 - Worker: Error de API - None - Fallo al conectar con la API: All connection attempts failed
2025-06-07 16:57:32,465 - __main__ - INFO - [MainThread] - main.py:128 - El worker de inicialización ha terminado.
2025-06-07 16:57:32,466 - __main__ - ERROR - [MainThread] - main.py:132 - No se pudo obtener la configuración del usuario. La aplicación se cerrará.
2025-06-07 16:57:32,480 - __main__ - INFO - [MainThread] - main.py:138 - Iniciando limpieza de la aplicación...
2025-06-07 16:57:32,480 - __main__ - INFO - [MainThread] - main.py:142 - Limpieza completada.
